"""YAML read/write helpers matching how Clash Verge persists its state.

Clash Verge writes its files with ``serde_yaml_ng`` and prepends a header
comment (``dirs.rs`` / ``verge.rs`` / ``clash.rs``)::

    # Clash Verge Config        <- verge.yaml
    # Generated by Clash Verge  <- config.yaml / clash-verge.yaml

Unknown keys are preserved on round-trip so a CLI edit never drops settings
added by a future Clash Verge release.
"""

from __future__ import annotations

import os
import tempfile
from pathlib import Path
from typing import Any

import yaml

VERGE_HEADER = "# Clash Verge Config"
CLASH_HEADER = "# Generated by Clash Verge"

_DEFAULT_HEADER = VERGE_HEADER


class YamlError(RuntimeError):
    """Raised when a YAML document cannot be read or written."""


class _TolerantLoader(yaml.SafeLoader):
    """SafeLoader that tolerates non-standard tags found in the wild.

    Clash configs occasionally carry tags such as ``!str`` or provider-specific
    markers. Unknown tags degrade to their plain scalar/structure value instead
    of aborting the whole load.
    """


def _unknown_tag(loader: yaml.Loader, tag_suffix: str, node: yaml.Node) -> Any:
    if isinstance(node, yaml.ScalarNode):
        return loader.construct_scalar(node)
    if isinstance(node, yaml.SequenceNode):
        return loader.construct_sequence(node)
    return loader.construct_mapping(node, deep=False)


_TolerantLoader.add_multi_constructor("", _unknown_tag)


def load_yaml(path: Path | str, default: Any = None) -> Any:
    """Load a YAML document, returning ``default`` when missing or empty.

    Raises ``YamlError`` when the file exists but is not a valid mapping, so
    corrupted state fails loudly instead of being silently replaced.
    """
    path = Path(path)
    if not path.exists():
        return default
    text = path.read_text(encoding="utf-8")
    if not text.strip():
        return default
    try:
        data = yaml.load(text, Loader=_TolerantLoader)
    except yaml.YAMLError as exc:
        raise YamlError(f"{path} is not valid YAML: {exc}") from exc
    if data is None:
        return default
    return data


def load_mapping(path: Path | str) -> dict[str, Any]:
    """Load a YAML mapping, defaulting to ``{}``."""
    data = load_yaml(path, default={})
    if not isinstance(data, dict):
        raise YamlError(
            f"{path} must contain a YAML mapping, got {type(data).__name__}."
        )
    return data


def dumps_yaml(data: Any, header: str | None = _DEFAULT_HEADER) -> str:
    """Serialize ``data`` to YAML, optionally preceded by a header comment."""
    body = yaml.safe_dump(
        data,
        default_flow_style=False,
        allow_unicode=True,
        sort_keys=False,
        width=4096,
    )
    if header:
        return f"{header}\n{body}"
    return body


def save_yaml(
    path: Path | str,
    data: Any,
    header: str | None = _DEFAULT_HEADER,
    make_backup: bool = False,
) -> str | None:
    """Atomically write ``data`` to ``path``.

    The write goes through a temp file in the same directory followed by
    ``os.replace``, so a crash mid-write can never leave a truncated config.

    Returns the previous file contents when ``make_backup`` is requested and
    the file already existed; otherwise ``None``.
    """
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)

    previous: str | None = None
    if make_backup and path.exists():
        previous = path.read_text(encoding="utf-8")

    content = dumps_yaml(data, header=header)
    fd, tmp_name = tempfile.mkstemp(
        dir=str(path.parent), prefix=f".{path.name}.", suffix=".tmp"
    )
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(content)
        os.replace(tmp_name, path)
    except BaseException:
        if os.path.exists(tmp_name):
            os.unlink(tmp_name)
        raise
    return previous
